site_name: 雨立（Ametatsu） Portfolio
docs_dir: src
site_dir: docs
theme:
  name: material
  language: ja
  palette:
    scheme: slate
  features:
    - navigation.footer
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.top
    # - navigation.tabs
    # - navigation.tabs.sticky
  palette:
    # - media: "(prefers-color-scheme)"
    #   toggle:
    #     icon: material/link
    #     name: Switch to light mode
    # - media: "(prefers-color-scheme: light)"
    #   scheme: default
    #   primary: grey
    #   accent: indigo
    #   toggle:
    #     icon: material/toggle-switch
    #     name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      # toggle:
      #   icon: material/toggle-switch-off
      #   name: Switch to system preference
  font:
    text: Roboto
    code: Roboto Mono

nav:
  - index.md
  - history.md
  - skill.md
markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ametatsu-dev/portfolio
    - icon: fontawesome/solid/blog
      link: https://ametatsu.hatenablog.jp/
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/ametatsu_dev
  analytics:
    provider: google
    property: G-SZJNFXL6Z4
copyright: Copyright &copy; 2024 -  雨立（Ametatsu）