[project]
name = "ametatsu-portfolio"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "mkdocs-material>=9.6.12",
]

[dependency-groups]
dev = [
    "pymdown-extensions>=10.12",
]
